### PR TITLE
Merge dicom archive repo with Loris-MRI; re-issued from PR#182

### PR DESCRIPTION
**Pull request by MounaSafiHarab**
Merging the dicom archive repo into Loris-MRI.

***Note for existing projects***: 
1) Make sure you backup the entire dicom-archive/ directory (including the .loris_mri/ directory within) before checking out this branch
2) Checkout the latest release (or download the new .zip form the release); might necessitate that you remove or move the dicom-archive/ directory otherwise checkout of the branch will abort.
3) copy back 
a) the .loris_mri/ directory (and the prod file within) to the dicom-archive/ directory, 
and 
b) your environment file

The README is also updated to remove step 2 (about the submodule).

Based off of the solution in @mohadesz's PR#182, except this pull request includes the files from the dicom-archive repo. The other pull request did not

### CODE REVIEW

**Comment by MounaSafiHarab** [comment]
This is based off of #181 (but since it is outdated now, and I could not check out the branch to test as it no longer exists), I recreated the pull request.
It is based off this link:

https://stackoverflow.com/questions/1759587/un-submodule-a-git-submodule 
(second solution proposes this), also documented in @mohadesz's RM#11981
```
git checkout aces/minor
git checkout -b MergeReposTest
git remote add submodule_origin git@github.com:aces/dicom-archive-tools.git
git fetch submodule_origin 
git merge -s ours --no-commit submodule_origin/master
git rm --cached submodule_path
git rm --cached dicom-archive/
git rm .gitmodules 
rm -rf dicom-archive/.git 
git add dicom-archive/
git commit -m 'removed submodule'
git remote rm submodule_origin
git push -u origin MergeReposTest 
```

**Comment by davidblader** [comment]
tested with an insert and everything went OK more or less
my only comment would be to explicitly state in the release notes that they will have to copy back the .loris_mri directory back into the dicom-archive directory or whatever is necessary to make their prod file accessible by the scripts

**Comment by MounaSafiHarab** [comment]
> tested with an insert and everything went OK
> my only comment would be to explicitly state in the release notes that they will have to copy back the .loris_mri directory back into the dicom-archive directory or whatever is necessary to make their prod file accessible by the scripts

@davidblader 
I updated the description of the pull request. let me know if this is good/clear enough to be added later in the 'how to upgrade' section for existing projects

**Comment by MounaSafiHarab** [comment]
> All good!

great, thanks!

**Pull request merged**
