### PR TITLE
[Moose] ConfigOB - more config options available via ConfigOB

### PR DESCRIPTION
**Pull request by cmadjar**
### Description

In this PR, all Config options that returns a string will be queried using the ConfigOB instead of the function in DBI.pm.

### CODE REVIEW

**Comment by cmadjar** [comment]
Manual tests performed:
- [ ] DTIPrepRegister.pl
- [ ] DTIPrep_pipeline.pl
- [ ] batch_uploads_imageuploader.pl
- [ ] batch_uploads_tarchive.pl
- [ ] BackPopulateSNRAndAcquisitionOrder.pl
- [ ] MakeNiiFilesBIDSCompliant.pl
- [ ] batch_run_defacing_script.pl
- [ ] batch_run_pipeline_qc_face_script.pl
- [ ] cleanupTarchives.pl
- [ ] create_nifti_bval_bvec.pl
- [ ] database_files_update.pl
- [ ] delete_imaging_upload.pl
- [ ] remove_jiv_data_from_db_and_filesystem.pl
- [ ] run_defacing_script.pl
- [ ] imaging_non_minc_insertion.pl
- [ ] mass_nii.pl
- [ ] mass_pic.pl
- [ ] minc_insertion.pl
- [ ] register_processed_data.pl
- [ ] tarchiveLoader.pl
- [ ] tarchive_validation.pl

**Comment by cmadjar** [comment]
@nicolasbrossard Totally agree! So weird... It looks like I missed a bunch of them when refactoring. I think I got them all now 🤞.

Hehe, I just realized that my branch is called call_ConfigOB_across_pipeline. It matches your comment :)

**Comment by nicolasbrossard** [comment]
@cmadjar I checked and the new functions you added in the `ConfigOB` are used throughout the entire pipeline 👍 The only exception is the script `tools/ProdToConfig.pl`, but it does not make sense to refactor this script until all the config constants it uses are defined in `ConfigOB.pm`.

**Comment by nicolasbrossard** [comment]
@cmadjar I wrote a little script to test the new functions in `ConfigOB` and they all work. I did not test the other scripts you modified though. Since you did these tests, I am approving this PR.

**Pull request merged**
