### PR TITLE
Update major with the latest 19.0-dev branch changes

### PR DESCRIPTION
**Pull request by MounaSafiHarab**
updating the major branch with the few changes merged into 19.0-dev sicne the last time major was updated

### CODE REVIEW

**Comment by MounaSafiHarab** [comment]
@cmadjar 
to have major up to date with 19.0-dev

p.s: just created minor branch as well, as per your request, from the 19.0-dev

**Comment by cmadjar** [comment]
Looks good. Merging it and testing major right away.

**Comment by MounaSafiHarab** [comment]
cool that you pushed the latest README merge to this commit!!!

**Comment by cmadjar** [comment]
Tested an upload via the imaging uploader, via batch_upload_tarchive. Also tested DTIPrep pipeline. All good 👍

**Pull request merged**
