### PR TITLE
Updating the imaging install script directory permissions

### PR DESCRIPTION
**Pull request by Jkat**
www-data needs to write to /data/incoming/

### CODE REVIEW

**Comment by mohadesz** [comment]
These changes are already made in the https://github.com/aces/Loris-MRI/pull/112 PR.

**Comment by Jkat** [comment]
Well then don't assign tickets to me because now I've wasted my time dealing with this.

This is also pull request #108, #112 comes after what I've already done, duplicate work.

**Comment by nicolasbrossard** [comment]
True. My bad. I didn't know you had a PR that did this already....  :(

**Comment by Jkat** [comment]
It's ok, sorry, wasn't directed at anyone specifically.

**Comment by samirdas** [comment]
Duplicated. Closing

**Pull request closed without merging**
