### PR TITLE
[bids_import] Add single electrode value instead of all electrode values

### PR DESCRIPTION
**Pull request by jeffersoncasimir**
This fixes a bug in electrode insertion, where more than one electrode was being inserted every time.

### CODE REVIEW

**Comment by christinerogers** [comment]
@jeffersoncasimir want to request a reviewer?  maybe laetitia or regis review this, if it's straightforward
Mark it high priority for the next release if that makes sense too.

**Review by regisoc — COMMENTED** [review]
Makes sense. If that is the case, lines containing electrode values ([L371](https://github.com/aces/Loris-MRI/blob/4e19fd9420921894a0a0983e7c5a0872a8c82906/python/lib/physiological.py#L371), [L412](https://github.com/aces/Loris-MRI/blob/4e19fd9420921894a0a0983e7c5a0872a8c82906/python/lib/physiological.py#L412C13-L412C29)) are not useful anymore and can be removed

**Comment by jeffersoncasimir** [comment]
Good point. I just removed those two references.

**Review by regisoc — APPROVED** [review]
LGTM

**Comment by christinerogers** [comment]
this PR is a `High Priority` `Bug fix` for the 26 release.

**Pull request merged**
