### PR TITLE
Corrected code that tests if two float numbers are equal

### PR DESCRIPTION
**Pull request by nicolasbrossard**
In MRI.pm, there was some code that used to test for the equality of float numbers using the == operator. This has been replaced by code that first formats the float numbers to 4 decimal places and compares them instead.

Reference [https://docstore.mik.ua/orelly/perl4/cook/ch02_04.htm](url)

### CODE REVIEW

**Comment by MounaSafiHarab** [comment]
@nicolasbrossard 

I tagged this for the next release so 1) we can discuss it at the next imaging meeting with others, and 2) I really will not be able to test it before this release (which is imminent).

**Comment by MounaSafiHarab** [comment]
discussed at the Loris Imaging meeting of october 13th; no need for a bugfix branch; minor and major might be enough for now

**Comment by MounaSafiHarab** [comment]
> Could you rebase your branch to aces:minor? When I checkout your branch, I still have the config settings fetched from the prod file instead of the Config table. Not sure why it does not show up on the Files changed front end of the PR...
> Thanks!

or to aces/major (they are all the same at this point in Loris-MRI), but since we will be releasing major (like Loris), please rebase on aces/major.

**Comment by nicolasbrossard** [comment]
I'll rebase on aces/major then. I'll let you know when it's done

**Pull request closed without merging**
